[tool.poetry]
name = "tornado-pyctuator-example"
version = "1.0.0"
description = "Example of using Pyctuator"
authors = [
    "Desmond Stonie <aneasystone@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.7"
psutil = { version = "^5.6" }
tornado = { version = "^6.0.4" }
pyctuator = { version = "^0.13.4" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

