# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package w/ make

on:
  push:
#    branches: [ master ]   ## TODO-YR: remove (debug)
  pull_request:
    branches: [ master ]

jobs:
  run_image:
    runs-on: [ubuntu-18.04]
    container:
      image: matanrubin/python-poetry:3.7

    steps:
       - uses: actions/checkout@v1.0.0
       - run: cd ..                 # cd to project root
       - run: make bootstrap
       - run: poetry update -vvv
       - run: poetry build -vvv
       - run: make package
       - run: poetry install --extras flask --extras fastapi --extras db --extras redis
       - run: make coverage

       # Install the extra psutil module and run the tests in "with psutil" env
       - run: poetry install --extras psutil
       - run: make test

       # Perform linting after all dependencies have been installed!
       # - run: make check   ## Fails!
       - run: poetry run pylint --exit-zero pyctuator tests
